export const coffeeDatabase = [
  {
    id: '1',
    name: 'El Capitan',
    price: 9.9,
    description: '250gr, 50% Brazil, 50% Ethiopea',
    taste: 'Toffee, Dark Chocolate, Light Floral',
    image: '/../public/ElCapitan.png',
  },
  {
    id: '2',
    name: 'Mexiko',
    price: 10.5,
    description: '250gr, 100% Mexico',
    taste: 'Marzipan, Nougat, Waffle',
    image: '/../public/Mexiko.png',
  },
  {
    id: '3',
    name: 'Mujeres Fuertes',
    price: 10.5,
    description: '250gr, Venezuela',
    taste: 'Raisin, Toffee, Dark Chocolate',
    image: '/../public/MujeresFuertes.png',
  },
  {
    id: '4',
    name: 'Nocciola',
    price: 9.9,
    description: '250gr, 70% Mexiko, 30% Tanzania',
    taste: 'Roasted Hazelnuts, Cocoa',
    image: '/../public/Nocciola.png',
  },
  {
    id: '5',
    name: 'Montecristo Organic',
    price: 9.9,
    description: '250gr, 100% Nicaragua',
    taste: 'Walnuts, Dark Chocolate, Peach',
    image: '/../public/Montecristo.png',
  },
  {
    id: '6',
    name: 'Primavera Decaf',
    price: 11.5,
    description: '250gr, 100% Guatemala',
    taste: 'Toffee, Chocolate, Chamomile ',
    image: '/../public/PrimaveraDecaf.png',
  },
];
